apiVersion: v1
kind: Secret
metadata:
  name: copilot-secret
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.copilot.secrets.OPENAI_API_KEY | b64enc }}
  OS_CLOUD_NAME: {{ .Values.copilot.secrets.OS_CLOUD_NAME | b64enc }}
  OS_AUTH_URL: {{ .Values.copilot.secrets.OS_AUTH_URL | b64enc }}
  OS_USERNAME: {{ .Values.copilot.secrets.OS_USERNAME | b64enc }}
  OS_PASSWORD: {{ .Values.copilot.secrets.OS_PASSWORD | b64enc }}
  OS_USER_DOMAIN_NAME: {{ .Values.copilot.secrets.OS_USER_DOMAIN_NAME | b64enc }}
  OS_PROJECT_NAME: {{ .Values.copilot.secrets.OS_PROJECT_NAME | b64enc }}
  OS_PROJECT_DOMAIN_NAME: {{ .Values.copilot.secrets.OS_PROJECT_DOMAIN_NAME | b64enc }}
