version: '3.7'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - bridged_net
  poc_genAI:
    image: <image_name>:<tag_name>
    container_name: openstack-chatbot-be
    hostname: openstack-chatbot-be
    restart: unless-stopped
    network_mode: host
    environment:
      OPENAI_API_KEY: ${openai_key}
      OS_CLOUD_NAME: ${}
      OS_AUTH_URL: ${}
      OS_USERNAME: ${}
      OS_PASSWORD: ${}
      OS_PROJECT_DOMAIN_NAME: ${}
      OS_PROJECT_NAME: ${}
      OS_USER_DOMAIN_NAME: ${}
networks:
  bridged_net:
    driver: bridge
